export const buildings = {
    estrada: {name: "estrada", price: 9, polution: 6, life: 7, metalIncome: 4, workerIncome: 4, pontoCientifico: 0, deck: "prefeitura"},
    ponte: {name: "ponte", price: 12, polution: 10, life: 15, metalIncome: 6, workerIncome: 3, pontoCientifico: 0, deck: "prefeitura"},
    ferrovia: {name: "ferrovia", price: 20, polution: 8, life: 10, metalIncome: 4, workerIncome: 6, pontoCientifico: 0, deck: "prefeitura"},
    porto: {name: "porto", price: 9, polution: 8, life: 10, metalIncome: 4, workerIncome: 2, pontoCientifico: 0, deck: "prefeitura"},
    banco: {name: "banco", price: 5, polution: 5, life: 0, metalIncome: 2, workerIncome: 0, pontoCientifico: 0, deck: "prefeitura"},
    parqueNatural: {name: "parque natural", price: 12, polution: -12, life: 20, metalIncome: 0, workerIncome: 0, pontoCientifico: 0, deck: "prefeitura"},
    parqueMaritimo: {name: "parque maritimo", price: 12, polution: -12, life: 20, metalIncome: 0, workerIncome: 0, pontoCientifico: 0, deck: "prefeitura"},
    aeroporto: {name: "aeroporto", price: 12, polution: 12, life: 20, metalIncome: 5, workerIncome: 2, pontoCientifico: 0, deck: "prefeitura"},
    centralEsgoto: {name: "central de tratamento de lixo e esgoto", price: 5, polution: -20, life: 10, metalIncome: 1, workerIncome: 1, pontoCientifico: 0, deck: "prefeitura"},
    parqueEolico: {name: "parque eólico", price: 30, polution: 10, life: 30, metalIncome: 10, workerIncome: 5, pontoCientifico: 1, deck: "prefeitura"},
    parqueSolar: {name: "parque solar", price: 30, polution: 10, life: 30, metalIncome: 10, workerIncome: 5, pontoCientifico: 1, deck: "prefeitura"},
    hidreletrica: {name: "usina hidrelétrica", price: 30, polution: 20, life: 25, metalIncome: 10, workerIncome: 5, pontoCientifico: 1, deck: "prefeitura"},
    usinaNuclear: {name: "usina nuclear", price: 50, polution: 10, life: 30, metalIncome: 15, workerIncome: 10, pontoCientifico: 1, deck: "prefeitura"},
    casa: {name: "casa", price: 2, polution: 1, life: 3, metalIncome: 0, workerIncome: 0, pontoCientifico: 0, deck: "recursos humanos"},
    praca: {name: "praça", price: 3, polution: -10, life: 2, metalIncome: 0, workerIncome: 0, pontoCientifico: 0, deck: "recursos humanos"},
    restaurante: {name: "restaurante", price: 5, polution: 1, life: 5, metalIncome: 0, workerIncome: 2, pontoCientifico: 0, deck: "recursos humanos"},
    teatro: {name: "teatro", price: 8, polution: 2, life: 10, metalIncome: 0, workerIncome: 4, pontoCientifico: 0, deck: "recursos humanos"},
    escola: {name: "escola", price: 11, polution: 2, life: 14, metalIncome: 0, workerIncome: 5, pontoCientifico: 0, deck: "recursos humanos"},
    creche: {name: "creche", price: 10, polution: 1, life: 15, metalIncome: 0, workerIncome: 5, pontoCientifico: 0, deck: "recursos humanos"},
    postoSaude: {name: "posto de saúde", price: 8, polution: 6, life: 20, metalIncome: 0, workerIncome: 4, pontoCientifico: 0, deck: "recursos humanos"},
    cinema: {name: "cinema", price: 13, polution: 1, life: 10, metalIncome: 0, workerIncome: 6, pontoCientifico: 0, deck: "recursos humanos"},
    laboratorio: {name: "laboratório de pesquisa", price: 16, polution: 6, life: 20, metalIncome: 0, workerIncome: 8, pontoCientifico: 1, deck: "recursos humanos"},
    universidade: {name: "universidade", price: 30, polution: 4, life: 30, metalIncome: 0, workerIncome: 15, pontoCientifico: 1, deck: "recursos humanos"},
    hospital: {name: "hospital", price: 30, polution: 8, life: 30, metalIncome: 0, workerIncome: 15, pontoCientifico: 0, deck: "recursos humanos"},
    apartamento: {name: "apartamento", price: 25, polution: 2, life: 30, metalIncome: 0, workerIncome: 0, pontoCientifico: 0, deck: "recursos humanos"},
    zonaPesca: {name: "zona de pesca", price: 6, polution: 3, life: 3, metalIncome: 3, workerIncome: 0, pontoCientifico: 0, deck: "diretores financeiros"},
    fazenda: {name: "fazenda", price: 8, polution: 3, life: 3, metalIncome: 4, workerIncome: 0, pontoCientifico: 0, deck: "diretores financeiros"},
    madeireira: {name: "madeireira", price: 6, polution: 5, life: 0, metalIncome: 3, workerIncome: 0, pontoCientifico: 0, deck: "diretores financeiros"},
    construtora: {name: "construtora", price: 8, polution: 5, life: 0, metalIncome: 4, workerIncome: 0, pontoCientifico: 0, deck: "diretores financeiros"},
    poloMetalurgico: {name: "polo metalúrgico", price: 10, polution: 4, life: 0, metalIncome: 5, workerIncome: 0, pontoCientifico: 0, deck: "diretores financeiros"},
    distribuidora: {name: "distribuidora de energia", price: 6, polution: 1, life: 8, metalIncome: 2, workerIncome: 0, pontoCientifico: 0, deck: "diretores financeiros"},
    poloAuto: {name: "polo automobilístico", price: 10, polution: 6, life: 0, metalIncome: 5, workerIncome: 0, pontoCientifico: 0, deck: "diretores financeiros"},
    poloMarinho: {name: "polo marinho", price: 16, polution: 12, life: 0, metalIncome: 8, workerIncome: 0, pontoCientifico: 0, deck: "diretores financeiros"},
    poloFarmaceutico: {name: "polo farmaceutico", price: 16, polution: 14, life: 0, metalIncome: 8, workerIncome: 0, pontoCientifico: 1, deck: "diretores financeiros"},
    centralInovação: {name: "central de inovação tecnológica", price: 16, polution: 15, life: 0, metalIncome: 8, workerIncome: 0, pontoCientifico: 1, deck: "diretores financeiros"},
    mineradora: {name: "mineradora", price: 30, polution: 20, life: 0, metalIncome: 15, workerIncome: 0, pontoCientifico: 0, deck: "diretores financeiros"},
    pocoPetroleo: {name: "poço de petróleo", price: 50, polution: 40, life: 0, metalIncome: 25, workerIncome: 0, pontoCientifico: 0, deck: "diretores financeiros"}    
}
