export let buildings = {
    estrada: 
        {name: "estrada", 
        price: 9, polution: 6, 
        life: 7, 
        metalIncome: 4,
        workerIncome: 4,
        pontoCientifico: 0,
        deck: "prefeitura",
        onField: {
            areaOne: 0,
            areaTwo: 0,
            areaThree: 0,
            areaFour: 0,
            areaFive: 0,
            areaSix: 0,
            areaSeven: 0,
        },
        total: 0,
        img: "../imagens/buildings/estrada.jpg"
    },

    ponte: 
        {name: "ponte",
        price: 12,
        polution: 10,
        life: 15,
        metalIncome: 6,
        workerIncome: 3,
        pontoCientifico: 0,
        deck: "prefeitura",
        onField: {
            areaOne: 0,
            areaTwo: 0,
            areaThree: 0,
            areaFour: 0,
            areaFive: 0,
            areaSix: 0,
            areaSeven: 0,
        },
        total: 0,
        img: "../imagens/buildings/ponte.jpg"
    },

    ferrovia: 
        {name: "ferrovia",
        price: 20,
        polution: 8,
        life: 10,
        metalIncome: 4,
        workerIncome: 6,
        pontoCientifico: 0,
        deck: "prefeitura",
        onField: {
            areaOne: 0,
            areaTwo: 0,
            areaThree: 0,
            areaFour: 0,
            areaFive: 0,
            areaSix: 0,
            areaSeven: 0,
        },
        total: 0,
        img: "../imagens/buildings/ferrovia.jpg"
    },

    porto: 
        {name: "porto",
        price: 9,
        polution: 8,
        life: 10,
        metalIncome: 4,
        workerIncome: 2,
        pontoCientifico: 0,
        deck: "prefeitura",
        onField: {
            areaOne: 0,
            areaTwo: 0,
            areaThree: 0,
            areaFour: 0,
            areaFive: 0,
            areaSix: 0,
            areaSeven: 0,
        },
        total: 0,
        img: "../imagens/buildings/porto.jpg"
    },

    banco: 
        {name: "banco",
        price: 5, 
        polution: 5, 
        life: 0, 
        metalIncome: 2, 
        workerIncome: 0, 
        pontoCientifico: 0, 
        deck: "prefeitura",
        onField: {
            areaOne: 0,
            areaTwo: 0,
            areaThree: 0,
            areaFour: 0,
            areaFive: 0,
            areaSix: 0,
            areaSeven: 0,
        },
        total: 0,
        img: "../imagens/buildings/banco.jpg"
    },

    parqueNatural: 
        {name: "parque natural",
        price: 12,
        polution: -12, 
        life: 20, 
        metalIncome: 0, 
        workerIncome: 0, 
        pontoCientifico: 0, 
        deck: "prefeitura",
        onField: {
            areaOne: 24,
            areaTwo: 24,
            areaThree: 0,
            areaFour: 0,
            areaFive: 24,
            areaSix: 24,
            areaSeven: 0,
        },
        total: 0,
        img: "../imagens/buildings/parque natural.jpg"
    },

    parqueMaritimo: 
        {name: "parque marítimo",
        price: 12, 
        polution: -12, 
        life: 20, 
        metalIncome: 0, 
        workerIncome: 0, 
        pontoCientifico: 0, 
        deck: "prefeitura",
        onField: {
            areaOne: 0,
            areaTwo: 0,
            areaThree: 0,
            areaFour: 0,
            areaFive: 0,
            areaSix: 0,
            areaSeven: 0,
        },
        total: 0,
        img: "../imagens/buildings/parque marinho.jpg"
    },

    aeroporto: 
        {name: "aeroporto",
        price: 12, 
        polution: 12, 
        life: 20, 
        metalIncome: 5, 
        workerIncome: 2, 
        pontoCientifico: 0, 
        deck: "prefeitura",
        onField: {
            areaOne: 0,
            areaTwo: 0,
            areaThree: 0,
            areaFour: 0,
            areaFive: 0,
            areaSix: 0,
            areaSeven: 0,
        },
        total: 0,
        img: "../imagens/buildings/aeroporto.jpg"
    },

    centralEsgoto: 
        {name: "central de tratamento de lixo e esgoto",
        price: 5,
        polution: -20,
        life: 10,
        metalIncome: 1,
        workerIncome: 1, 
        pontoCientifico: 0, 
        deck: "prefeitura",
        onField: {
            areaOne: 0,
            areaTwo: 0,
            areaThree: 0,
            areaFour: 0,
            areaFive: 0,
            areaSix: 0,
            areaSeven: 0,
        },
        total: 0,
        img: "../imagens/buildings/coleta.jpg"
    },

    parqueEolico: 
        {name: "parque eólico", 
        price: 30, 
        polution: 10, 
        life: 30, 
        metalIncome: 10, 
        workerIncome: 5, 
        pontoCientifico: 1, 
        deck: "prefeitura",
        onField: {
            areaOne: 0,
            areaTwo: 0,
            areaThree: 0,
            areaFour: 15,
            areaFive: 0,
            areaSix: 15,
            areaSeven: 0,
        },
        total: 0,
        img: "../imagens/buildings/eolico.jpg"
    },

    parqueSolar: 
        {name: "parque solar", 
        price: 30, 
        polution: 10, 
        life: 30, 
        metalIncome: 10, 
        workerIncome: 5, 
        pontoCientifico: 1, 
        deck: "prefeitura",
        onField: {
            areaOne: 0,
            areaTwo: 0,
            areaThree: 0,
            areaFour: 15,
            areaFive: 0,
            areaSix: 15,
            areaSeven: 0,
        },
        total: 0,
        img: "../imagens/buildings/solar.jpg"
    },
        
    hidreletrica: 
        {name: "usina hidrelétrica", 
        price: 30, 
        polution: 20, 
        life: 25, 
        metalIncome: 10, 
        workerIncome: 5, 
        pontoCientifico: 1, 
        deck: "prefeitura",
        onField: {
            areaOne: 0,
            areaTwo: 0,
            areaThree: 0,
            areaFour: 15,
            areaFive: 0,
            areaSix: 0,
            areaSeven: 0,
        },
        total: 0,
        img: "../imagens/buildings/hidreletrica.jpg"
    },

    usinaNuclear: 
        {name: "usina nuclear", 
        price: 50, 
        polution: 10, 
        life: 30, 
        metalIncome: 15, 
        workerIncome: 10, 
        pontoCientifico: 1, 
        deck: "prefeitura",
        onField: {
            areaOne: 0,
            areaTwo: 0,
            areaThree: 0,
            areaFour: 0,
            areaFive: 0,
            areaSix: 0,
            areaSeven: 0,
        },
        total: 0,
        img: "../imagens/buildings/nuclear.jpg"
    },

    casa: 
        {name: "casa", 
        price: 2, 
        polution: 1, 
        life: 3, 
        metalIncome: 0, 
        workerIncome: 0, 
        pontoCientifico: 0, 
        deck: "recursos humanos",
        onField: {
            areaOne: 2,
            areaTwo: 0,
            areaThree: 2,
            areaFour: 0,
            areaFive: 0,
            areaSix: 2,
            areaSeven: 0,
        },
        total: 0,
        img: "../imagens/buildings/casa.jpg"
    },

    praça: 
        {name: "praça", 
        price: 3, 
        polution: -10, 
        life: 2, 
        metalIncome: 0, 
        workerIncome: 0, 
        pontoCientifico: 0, 
        deck: "recursos humanos",
        onField: {
            areaOne: 7,
            areaTwo: 0,
            areaThree: 7,
            areaFour: 0,
            areaFive: 0,
            areaSix: 7,
            areaSeven: 0,
        },
        total: 0,
        img: "../imagens/buildings/praça.jpg"
    },

    restaurante: 
        {name: "restaurante", 
        price: 5, 
        polution: 1, 
        life: 5, 
        metalIncome: 0, 
        workerIncome: 2, 
        pontoCientifico: 0, 
        deck: "recursos humanos",
        onField: {
            areaOne: 2,
            areaTwo: 0,
            areaThree: 2,
            areaFour: 0,
            areaFive: 0,
            areaSix: 2,
            areaSeven: 0,
        },
        total: 0,
        img: "../imagens/buildings/restaurante.jpg"
    },

    teatro: 
        {name: "teatro",
        price: 8, 
        polution: 2, 
        life: 10, 
        metalIncome: 0, 
        workerIncome: 4, 
        pontoCientifico: 0, 
        deck: "recursos humanos",
        onField: {
            areaOne: 0,
            areaTwo: 0,
            areaThree: 4,
            areaFour: 0,
            areaFive: 0,
            areaSix: 4,
            areaSeven: 0,
        },
        total: 0,
        img: "../imagens/buildings/teatro.jpg"
    },

    escola: 
        {name: "escola", 
        price: 11, 
        polution: 2, 
        life: 14, 
        metalIncome: 0, 
        workerIncome: 5, 
        pontoCientifico: 0, 
        deck: "recursos humanos",
        onField: {
            areaOne: 4,
            areaTwo: 0,
            areaThree: 4,
            areaFour: 0,
            areaFive: 0,
            areaSix: 4,
            areaSeven: 0,
        },
        total: 0,
        img: "../imagens/buildings/escola.jpg"
    },

    creche: 
        {name: "creche", 
        price: 10, 
        polution: 1, 
        life: 15, 
        metalIncome: 0, 
        workerIncome: 5, 
        pontoCientifico: 0, 
        deck: "recursos humanos",
        onField: {
            areaOne: 2,
            areaTwo: 0,
            areaThree: 2,
            areaFour: 0,
            areaFive: 0,
            areaSix: 2,
            areaSeven: 0,
        },
        total: 0,
        img: "../imagens/buildings/creche.jpg"
    },
        
    postoSaude: 
        {name: "posto de saúde", 
        price: 8, 
        polution: 6, 
        life: 20, 
        metalIncome: 0, 
        workerIncome: 4, 
        pontoCientifico: 0, 
        deck: "recursos humanos",
        onField: {
            areaOne: 0,
            areaTwo: 0,
            areaThree: 4,
            areaFour: 0,
            areaFive: 0,
            areaSix: 4,
            areaSeven: 0,
        },
        total: 0,
        img: "../imagens/buildings/posto.jpg"
    },

    cinema: 
        {name: "cinema", 
        price: 13, 
        polution: 1, 
        life: 10, 
        metalIncome: 0, 
        workerIncome: 6, 
        pontoCientifico: 0, 
        deck: "recursos humanos",
        onField: {
            areaOne: 0,
            areaTwo: 0,
            areaThree: 5,
            areaFour: 0,
            areaFive: 0,
            areaSix: 5,
            areaSeven: 0,
        },
        total: 0,
        img: "../imagens/buildings/cinema.jpg"
    },

    laboratorio: 
        {name: "laboratório de pesquisa", 
        price: 16, 
        polution: 6, 
        life: 20, 
        metalIncome: 0, 
        workerIncome: 8, 
        pontoCientifico: 1, 
        deck: "recursos humanos",
        onField: {
            areaOne: 0,
            areaTwo: 0,
            areaThree: 4,
            areaFour: 0,
            areaFive: 0,
            areaSix: 4,
            areaSeven: 0,
        },
        total: 0,
        img: "../imagens/buildings/lab.jpg"
    },

    universidade: 
        {name: "universidade", 
        price: 30, 
        polution: 4, 
        life: 30, 
        metalIncome: 0, 
        workerIncome: 15, 
        pontoCientifico: 1, 
        deck: "recursos humanos",
        onField: {
            areaOne: 5,
            areaTwo: 0,
            areaThree: 5,
            areaFour: 0,
            areaFive: 0,
            areaSix: 5,
            areaSeven: 0,
        },
        total: 0,
        img: "../imagens/buildings/universidade.jpg"
    },

    hospital: 
        {name: "hospital", 
        price: 30, 
        polution: 8, 
        life: 30, 
        metalIncome: 0, 
        workerIncome: 15, 
        pontoCientifico: 0, 
        deck: "recursos humanos",
        onField: {
            areaOne: 0,
            areaTwo: 0,
            areaThree: 5,
            areaFour: 0,
            areaFive: 0,
            areaSix: 5,
            areaSeven: 0,
        },
        total: 0,
        img: "../imagens/buildings/hospital.jpg"
    },

    apartamento: 
        {name: "apartamento", 
        price: 25, 
        polution: 2, 
        life: 30, 
        metalIncome: 0, 
        workerIncome: 0, 
        pontoCientifico: 0, 
        deck: "recursos humanos",
        onField: {
            areaOne: 5,
            areaTwo: 0,
            areaThree: 5,
            areaFour: 0,
            areaFive: 0,
            areaSix: 5,
            areaSeven: 0,
        },
        total: 0,
        img: "../imagens/buildings/apartamento.jpg"
    },

    zonaPesca: 
        {name: "zona de pesca", 
        price: 6, 
        polution: 3, 
        life: 3, 
        metalIncome: 3, 
        workerIncome: 0, 
        pontoCientifico: 0, 
        deck: "diretores financeiros",
        onField: {
            areaOne: 0,
            areaTwo: 0,
            areaThree: 0,
            areaFour: 0,
            areaFive: 0,
            areaSix: 0,
            areaSeven: 0,
        },
        total: 0,
        img: "../imagens/buildings/pesca.jpg"
    },

    fazenda: 
        {name: "fazenda", 
        price: 8, 
        polution: 3, 
        life: 3, 
        metalIncome: 4, 
        workerIncome: 0, 
        pontoCientifico: 0, 
        deck: "diretores financeiros",
        onField: {
            areaOne: 12,
            areaTwo: 12,
            areaThree: 0,
            areaFour: 4,
            areaFive: 12,
            areaSix: 12,
            areaSeven: 0,
        },
        total: 0,
        img: "../imagens/buildings/fazenda.jpg"
    },

    madeireira: 
        {name: "madeireira", 
        price: 6, 
        polution: 5, 
        life: 0, 
        metalIncome: 3, 
        workerIncome: 0, 
        pontoCientifico: 0, 
        deck: "diretores financeiros",
        onField: {
            areaOne: 0,
            areaTwo: 0,
            areaThree: 0,
            areaFour: 0,
            areaFive: 0,
            areaSix: 0,
            areaSeven: 0,
        },
        total: 0,
        img: "../imagens/buildings/madeireira.jpg"
    },

    construtora: 
        {name: "construtora", 
        price: 8, 
        polution: 5, 
        life: 0, 
        metalIncome: 4, 
        workerIncome: 0, 
        pontoCientifico: 0, 
        deck: "diretores financeiros",
        onField: {
            areaOne: 0,
            areaTwo: 0,
            areaThree: 0,
            areaFour: 0,
            areaFive: 0,
            areaSix: 0,
            areaSeven: 0,
        },
        total: 0,
        img: "../imagens/buildings/construtora.jpg"
    },

    poloMetalurgico: 
        {name: "polo metalúrgico", 
        price: 10, 
        polution: 4, 
        life: 0, 
        metalIncome: 5, 
        workerIncome: 0, 
        pontoCientifico: 0, 
        deck: "diretores financeiros",
        onField: {
            areaOne: 8,
            areaTwo: 8,
            areaThree: 0,
            areaFour: 8,
            areaFive: 8,
            areaSix: 0,
            areaSeven: 0,
        },
        total: 0,
        img: "../imagens/buildings/metalurgico.jpg"
    },

    distribuidora: 
        {name: "distribuidora de energia", 
        price: 6, 
        polution: 1, 
        life: 8, 
        metalIncome: 2, 
        workerIncome: 0, 
        pontoCientifico: 0, 
        deck: "diretores financeiros",
        onField: {
            areaOne: 0,
            areaTwo: 0,
            areaThree: 0,
            areaFour: 0,
            areaFive: 0,
            areaSix: 0,
            areaSeven: 0,
        },
        total: 0,
        img: "../imagens/buildings/distribuidora.jpg"
    },

    poloAuto: 
        {name: "polo automobilístico", 
        price: 10, 
        polution: 6, 
        life: 0, 
        metalIncome: 5, 
        workerIncome: 0, 
        pontoCientifico: 0, 
        deck: "diretores financeiros",
        onField: {
            areaOne: 0,
            areaTwo: 0,
            areaThree: 0,
            areaFour: 0,
            areaFive: 0,
            areaSix: 0,
            areaSeven: 0,
        },
        total: 0,
        img: "../imagens/buildings/automobilistico.jpg"
    },

    poloMarinho: 
        {name: "polo marinho", 
        price: 16, 
        polution: 12, 
        life: 0, 
        metalIncome: 8, 
        workerIncome: 0, 
        pontoCientifico: 0, 
        deck: "diretores financeiros",
        onField: {
            areaOne: 0,
            areaTwo: 0,
            areaThree: 0,
            areaFour: 0,
            areaFive: 0,
            areaSix: 0,
            areaSeven: 0,
        },
        total: 0,
        img: "../imagens/buildings/maritimo.jpg"
    },

    poloFarmaceutico: 
        {name: "polo farmaceutico", 
        price: 16, 
        polution: 14, 
        life: 0, 
        metalIncome: 8, 
        workerIncome: 0, 
        pontoCientifico: 1, 
        deck: "diretores financeiros",
        onField: {
            areaOne: 4,
            areaTwo: 4,
            areaThree: 0,
            areaFour: 4,
            areaFive: 4,
            areaSix: 0,
            areaSeven: 0,
        },
        total: 0,
        img: "../imagens/buildings/farmaceutico.jpg"
    },

    centralInovação: 
        {name: "central de inovação tecnológica", 
        price: 16, 
        polution: 15, 
        life: 0, 
        metalIncome: 8, 
        workerIncome: 0, 
        pontoCientifico: 1, 
        deck: "diretores financeiros",
        onField: {
            areaOne: 4,
            areaTwo: 4,
            areaThree: 0,
            areaFour: 4,
            areaFive: 4,
            areaSix: 0,
            areaSeven: 0,
        },
        total: 0,
        img: "../imagens/buildings/tecnologica.jpg"
    },

    mineradora: 
        {name: "mineradora", 
        price: 30, 
        polution: 20, 
        life: 0, 
        metalIncome: 15, 
        workerIncome: 0, 
        pontoCientifico: 0, 
        deck: "diretores financeiros",
        onField: {
            areaOne: 0,
            areaTwo: 0,
            areaThree: 0,
            areaFour: 0,
            areaFive: 5,
            areaSix: 0,
            areaSeven: 0,
        },
        total: 0,
        img: "../imagens/buildings/mineradora.jpg"
    },

    pocoPetroleo: 
        {name: "poço de petróleo", 
        price: 50,
        polution: 40, 
        life: 0, 
        metalIncome: 25, 
        workerIncome: 0, 
        pontoCientifico: 0, 
        deck: "diretores financeiros",
        onField: {
            areaOne: 0,
            areaTwo: 0,
            areaThree: 0,
            areaFour: 0,
            areaFive: 0,
            areaSix: 0,
            areaSeven: 0,
        },
        total: 0,
        img: "../imagens/buildings/petroleo.jpg"
    }    
}


export const characters = {
    prefeitura: 
        {name: "prefeitura", 
        inicialMetalResource: 50, 
        inicialWorkerResource: 25},
    rh: 
        {name: "Diretores de Recursos Humanos", 
        inicialMetalResource: 25,
        inicialWorkerResource: 15},

    df: 
        {name: "Diretores de Recursos Financeiros", 
        inicialMetalResource: 25,
        inicialWorkerResource: 15}
}